# Generated by Django 5.0.7 on 2024-07-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Custumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('by_date', models.DateTimeField()),
                ('Car_name', models.ManyToManyField(to='app.car_models')),
            ],
        ),
    ]
